language: python
python:
- '2.7'
before_install:
- sudo apt-get install python-pythonmagick libpq-dev python-dev libopencv-dev python-opencv pdftk
- sudo apt-get build-dep python-opencv
- pip install pyopencv
- pip install pyPdf
- pip install python-magic
- pip install coverage
- pip install coveralls
install:
- python setup.py install
script:
- coverage run setup.py test
after_success:
- coveralls
notifications:
  email: false
sudo: true

